### ISSUE TITLE
自有属性枚举顺序 描述有误

### ISSUE THREAD

**Issue by summer1874** [hyy1115/ES6-learning#10]
应当是：
首先遍历所有数值键，按照数值升序排列。
其次遍历所有字符串键，按照加入时间升序排列。
最后遍历所有 Symbol 键，按照加入时间升序排列。

摘于 《ECMAScript 6入门》

**Comment by hyy1115** [comment]
ECMAScript草案中关于getOwnPropertyNames用法的描述如下，根据官方提供的步骤来看，先遍历所有的key，如果满足key的类型等于String or Symbol，就添加到nameList中，遍历完成之后再执行 CreateArrayFromList函数。从此处看，第一步遍历不会去排序，排序是全部遍历完成再做的处理。
所以，我不知道你说的《ECMAScript 6入门》的3步遍历是根据什么得出来的？
```text
Object.getOwnPropertyNames ( O )
When the getOwnPropertyNames function is called, the following steps are taken:
Return ? GetOwnPropertyKeys(O, String).


Runtime Semantics: GetOwnPropertyKeys(O, Type)
The abstract operation GetOwnPropertyKeys is called with arguments O and Type where O is an Object and Type is one of the ECMAScript specification types String or Symbol. The following steps are taken:
Let obj be ? ToObject(O).
Let keys be ? obj.[[OwnPropertyKeys]]().
Let nameList be a new empty List.
For each element nextKey of keys in List order, do
If Type(nextKey) is Type, then
Append nextKey as the last element of nameList.
Return CreateArrayFromList(nameList).
```

**Comment by summer1874** [comment]
>上面的例子的输出结果都有个规律，就是数字提前，按顺序排序，接着是字母排序。而这种行为也是ES6新增的标准。你还可以自己测试一下其他方法是不是也支持枚举自动排序。比如Object.keys(), for in 等。

```js
const obj = {
  id:1,
  name:'winni',
  a:1,
  1:1,
  10:10,
  2:2,
}
Object.getOwnPropertyNames(obj);//["1", "2", "10", "id", "name", "a"]
//不会依照字母排序，而是按照加入时间升序排列
```
[《ECMAScript 6入门》 属性的遍历](http://es6.ruanyifeng.com/#docs/object#%E5%B1%9E%E6%80%A7%E7%9A%84%E5%8F%AF%E6%9E%9A%E4%B8%BE%E6%80%A7%E5%92%8C%E9%81%8D%E5%8E%86 )

**Comment by hyy1115** [comment]
的确，字母排序是不对的，《ECMAScript 6入门》的描述也是不对的，以ECMA官方提供的标准为参考，如果你找到了自有枚举属性排序的全部规律，欢迎提PR。
