### ISSUE TITLE
 第四章，Object.assign方法实例错误

### ISSUE THREAD

**Issue by queenzjl** [hyy1115/ES6-learning#11]
在介绍object.assign方法时列举的”Component的例子“经测试是错误的，报错“`Uncaught TypeError: MyComponent.render is not a function`”。而且注释中写的“ 新对象继承了Component的所有方法和属性。” 我认为这句话不合理。object.assign 应该只是复制， 不是继承

**Comment by hyy1115** [comment]
你可以把它改正确然后commit吗？

**Comment by queenzjl** [comment]
1、首先这个例子我不建议这样写。要么用class创建对象，要么用原型链，不要这样混合用。
2、Object.assign()并不能复制源对象的所有方法和属性。只复制源对象中可枚举的属性和对象自身的属性。
3、我的理解是object.assign()方法不能复制原型链上的方法。最近也是刚学es6，好多地方也理解的不到位，彻底搞懂这部分后可以继续讨论哈哈
