### ISSUE TITLE
第九章：9、JavaScript中的类class的‘内建对象的继承‘小节

### ISSUE THREAD

**Issue by hkaikai** [hyy1115/ES6-learning#13]
`class MyArray extends Array { }`
`let colors = new Array()`
`colors[0] = "1"`
`console.log(colors) // [1]`
是不是要改成？
`class MyArray extends Array { }`
`let colors = new MyArray() // 修改成MyArray`
`colors[0] = "1"`
`console.log(colors) // [1]`

**Comment by hyy1115** [comment]
是的，你可以提交PR
