### ISSUE TITLE
第9章，JavaScript中的类class例子有误

### ISSUE THREAD

**Issue by fengyun2** [hyy1115/ES6-learning#14]
![image](https://user-images.githubusercontent.com/8147202/44941997-bbcc3c00-adda-11e8-9f1e-513fe7fb39d6.png)

![image](https://user-images.githubusercontent.com/8147202/44942022-2f6e4900-addb-11e8-8073-28ab697d7920.png)

**Comment by hyy1115** [comment]
这一块之前没有注意到，应该把a.printId()赋值给一个变量x，使用该变量x来访问next()。
```javascript
let a = new A()
let x = a.printId()

x.next()
x.next()
x.next()
```
