### ISSUE TITLE
第一章 const描述补充

### ISSUE THREAD

**Issue by mythxiaoai** [hyy1115/ES6-learning#6]
第一章
const   
const虽然是常量，不允许修改默认赋值，但如果定义的是对象Object，那么可以修改对象内部的属性值。

补充下
const虽然是常量，不允许修改默认赋值，但如果定义的是对象Object， 是允许改值的并且也能增加和减少值（delete type.b或type.c="3"都是可以的）,但是不能更改对象的内存地址（ type=[] 或2.type={}等都是不可以的）

**Comment by hyy1115** [comment]
欢迎提PR，fork项目，然后clone到你的本地，修改之后推送，再申请合并。
