### ISSUE TITLE
WeakMap示例代码有误

### ISSUE THREAD

**Issue by YangGoldDragon** [hyy1115/ES6-learning#9]
let map = new WeakMap();
    const key = document.querySelector('.header');
    map.set(key, '这是个什么玩意');
    
    map.get(key) // "这是个什么玩意"
    
    //移除该元素
    key.parentNode.removeChild(key);
    key = null;  

最后一行代码编译运行的时候是报错的，你前面用了const定义的，后面怎么可以再赋值为其它值。应该使用let。

**Comment by hyy1115** [comment]
恭喜你，找到隐藏副本，打开思考的大门。

**Comment by YangGoldDragon** [comment]
看阮一峰的es6太过于细节繁杂了，找不到一个很好的清晰脉络，先看一下阮一峰的，再看一下你的学习笔记，对es6的掌握就有一个很清晰的知识体系了，你的笔记对我帮助很大。

**Comment by hyy1115** [comment]
你擅长自我思考问题，才会觉得有启发。
